mysql:
  host: "127.0.0.1"
  user: "root"
  password: ""
  database: "my_server"

language: "en"

messages:
  levelup: "§bYou are now level §a{LEVEL}§b in {JOB}§b."

menu:
  title: "Jobs"
  job-lore: "§bLevel §a{LEVEL}\n§a{CURRENT_EXP} / {TARGET_EXP}§b exp\n§7Click for skills and details"
  job-lore-selected: "§bLevel §a{LEVEL}\n§a{CURRENT_EXP} / {TARGET_EXP}§b exp\n§a{TOTAL_EXP}§b total exp"
  hidden-skill:
    description: "§cRequires level §6{LEVEL}"

woodcutting:
  name: "§2Woodcutting"
  bar-color: "GREEN"
  icon: "IRON_AXE"
  skills:
    careful:
      name: "§6Careful"
      icon: "GOLDEN_AXE"
      description: "§bYour axes break §a{BONUS}%§b slower.\n§7Increases with your level."
    gatherer:
      name: "§6Gatherer"
      icon: "OAK_LOG"
      description: "§a{BONUS}%§b chance to double your logs.\n§7Increases with your level."
    defoliator:
      name: "§6Defoliator"
      icon: "OAK_LEAVES"
      description: "§bAxes break §anatural leaves§b instantly.\n§aLeaves§b no longer reduce durability."
    calculator1:
      name: "§6Calculator I"
      icon: "OAK_SAPLING"
      description: "§bBreak small trees in a single chop.\n§bCooldown: §a{COOLDOWN}§b seconds\n§7Cooldown decreases with your level."
    calculator2:
      name: "§6Calculator II"
      icon: "BIRCH_SAPLING"
      description: "§bBreak medium trees in a single chop.\n§bCooldown: §a{COOLDOWN}§b seconds\n§7Cooldown decreases with your level."
    calculator3:
      name: "§6Calculator III"
      icon: "JUNGLE_SAPLING"
      description: "§bBreak large trees in a single chop.\n§bCooldown: §a{COOLDOWN}§b seconds\n§7Cooldown decreases with your level."

mining:
  name: "§7Mining"
  bar-color: "WHITE"
  icon: "IRON_PICKAXE"
  skills:
    careful:
      name: "§6Careful"
      icon: "GOLDEN_PICKAXE"
      description: "§bYour pickaxes break §a{BONUS}%§b slower.\n§7Increases with your level."
    gatherer:
      name: "§6Gatherer"
      icon: "IRON_ORE"
      description: "§a{BONUS}%§b chance to double your ores.\n§7Increases with your level."
    lava-smelt:
      name: "§6Lava smelting"
      icon: "LAVA_BUCKET"
      description: "§bSmelt iron and gold ores instantly\n§b if you have a §abucket of lava\n§b in your inventory."
    inspiration:
      name: "§6Inspiration"
      icon: "REDSTONE_TORCH"
      description: "§bHaste during §a{TIME}§b seconds\n §bafter mining an ore.\n§7Duration increases with your level."
    lava-resistance:
      name: "§6Heat resistance"
      icon: "FIRE_CHARGE"
      description: "§bFire resistance during §a{TIME}§b seconds\n §bwhen touching lava.\n§bCooldown: §a{COOLDOWN}§b seconds\n§7Duration increases with your level.\n§7Cooldown decreases with your level."

farming:
  name: "§aFarming"
  bar-color: "GREEN"
  icon: "IRON_HOE"
  skills:
    careful:
      name: "§6Careful"
      icon: "GOLDEN_HOE"
      description: "§bYour hoes break §a{BONUS}%§b slower.\n§7Increases with your level."
    gatherer:
      name: "§6Gatherer"
      icon: "CARROT"
      description: "§a{BONUS}%§b chance to double your harvests.\n§7Increases with your level."
    crops-feather:
      name: "§6As a feather"
      icon: "FEATHER"
      description: "§bJumping on §acrops§b no longer\n§bbreak them."
    negate-damage:
      name: "§6Cactus tamer"
      icon: "CACTUS"
      description: "§bPlants like §acactus§b no longer\n§bdamage you."

fishing:
  name: "§3Fishing"
  bar-color: "BLUE"
  icon: "FISHING_ROD"
  hint-deep-water: "§bFish in §3deep water§b to get more loot and experience!"
  skills:
    careful:
      name: "§6Careful"
      icon: "FISHING_ROD"
      description: "§bYour fishing rods break §a{BONUS}%§b slower.\n§7Increases with your level."
    gatherer:
      name: "§6Gatherer"
      icon: "COD"
      description: "§a{BONUS}%§b chance to catch two fish.\n§7Increases with your level."
    impatient:
      name: "§6Impatient"
      icon: "CLOCK"
      description: "§bReduce the wait time by §a{BONUS}%§b.\n§7Improves with your level."

hunting:
  name: "§cHunting"
  bar-color: "RED"
  icon: "IRON_SWORD"
  skills:
    careful:
      name: "§6Careful"
      icon: "GOLDEN_SWORD"
      description: "§bYour swords and bows break §a{BONUS}%§b slower.\n§7Increases with your level."
    egg-drop:
      name: "§6Egg hunter"
      icon: "SHEEP_SPAWN_EGG"
      description: "§a{BONUS}%§b chance to drop animal eggs.\n§7Increases with your level."
    fall-damage:
      name: "§6Smooth fall"
      icon: "FEATHER"
      description: "§bReduce fall damage by §a{BONUS}%§b.\n§7Increases with your level."
    mine-spawner:
      name: "§6Spawner miner"
      icon: "SPAWNER"
      description: "§bYou can loot the spawners you break."
    inspiration:
      name: "§6Inspiration"
      icon: "REDSTONE_TORCH"
      description: "§bStrength during §a{TIME}§b seconds\n §bafter killing a mob.\n§7Duration increases with your level."
    explosion-survivor:
      name: "§6Explosion survivor"
      icon: "TNT"
      description: "§bSurvive an explosion that would kill you.\n§bCooldown: §a{COOLDOWN}§b seconds\n§7Cooldown decreases with your level."

enchanting:
  name: "§cEnchanting"
  bar-color: "PURPLE"
  icon: "BOOK"
